parameters:
    pim_excel_connector.excel.builder.factory.class:        Pim\Bundle\ExcelConnectorBundle\Excel\Builder\ExcelBuilderFactory
    pim_excel_connector.excel.builder.class:                Pim\Bundle\ExcelConnectorBundle\Excel\Builder\ExcelBuilder
    pim_excel_connector.excel.builder.product_family.class: Pim\Bundle\ExcelConnectorBundle\Excel\Builder\ProductFamilyExcelBuilder

    pim_excel_connector.excel.reader.archive.class:               Pim\Bundle\ExcelConnectorBundle\Excel\Reader\Archive
    pim_excel_connector.excel.reader.archive_loader.class:        Pim\Bundle\ExcelConnectorBundle\Excel\Reader\ArchiveLoader
    pim_excel_connector.excel.reader.content_cache.class:         Pim\Bundle\ExcelConnectorBundle\Excel\Reader\ContentCache
    pim_excel_connector.excel.reader.content_cache_loader.class:  Pim\Bundle\ExcelConnectorBundle\Excel\Reader\ContentCacheLoader
    pim_excel_connector.excel.reader.relationships.class:         Pim\Bundle\ExcelConnectorBundle\Excel\Reader\Relationships
    pim_excel_connector.excel.reader.relationships_loader.class:  Pim\Bundle\ExcelConnectorBundle\Excel\Reader\RelationshipsLoader
    pim_excel_connector.excel.reader.worksheet_list_reader.class: Pim\Bundle\ExcelConnectorBundle\Excel\Reader\WorksheetListReader
    pim_excel_connector.excel.reader.row_iterator.class:          Pim\Bundle\ExcelConnectorBundle\Excel\Reader\Relationships
    pim_excel_connector.excel.reader.row_iterator_factory.class:  Pim\Bundle\ExcelConnectorBundle\Excel\Reader\RowIteratorFactory
    pim_excel_connector.excel.reader.workbook.class:              Pim\Bundle\ExcelConnectorBundle\Excel\Reader\Workbook
    pim_excel_connector.excel.reader.workbook_loader.class:       Pim\Bundle\ExcelConnectorBundle\Excel\Reader\WorkbookLoader

services:
    pim_excel_connector.excel.builder.factory:
        class: %pim_excel_connector.excel.builder.factory.class%
        arguments:
            - '@service_container'

    pim_excel_connector.excel.reader.archive_loader:
        class: %pim_excel_connector.excel.reader.archive_loader.class%
        arguments:
            - %pim_excel_connector.excel.reader.archive.class%

    pim_excel_connector.excel.reader.content_cache_loader:
        class: %pim_excel_connector.excel.reader.content_cache_loader.class%
        arguments:
            - %pim_excel_connector.excel.reader.content_cache.class%

    pim_excel_connector.excel.reader.relationships_loader:
        class: %pim_excel_connector.excel.reader.relationships_loader.class%
        arguments:
            - %pim_excel_connector.excel.reader.relationships.class%

    pim_excel_connector.excel.reader.worksheet_list_reader:
        class: %pim_excel_connector.excel.reader.worksheet_list_reader.class%

    pim_excel_connector.excel.reader.row_iterator_factory:
        class: %pim_excel_connector.excel.reader.row_iterator_factory.class%
        arguments:
            - %pim_excel_connector.excel.reader.row_iterator.class%

    pim_excel_connector.excel.reader.workbook_loader:
        class: %pim_excel_connector.excel.reader.workbook_loader.class%
        arguments:
            - @pim_excel_connector.excel.reader.archive_loader
            - @pim_excel_connector.excel.reader.relationships_loader
            - @pim_excel_connector.excel.reader.content_cache_loader
            - @pim_excel_connector.excel.reader.worksheet_list_reader
            - @pim_excel_connector.excel.reader.row_iterator_factory
            - %pim_excel_connector.excel.reader.workbook.class%
