parameters:
    pim_excel_connector.excel.helper.class:                 Pim\Bundle\ExcelConnectorBundle\Excel\ExcelHelper
    pim_excel_connector.excel.builder.factory.class:        Pim\Bundle\ExcelConnectorBundle\Excel\ExcelBuilderFactory
    pim_excel_connector.excel.builder.class:                Pim\Bundle\ExcelConnectorBundle\Excel\ExcelBuilder
    pim_excel_connector.excel.builder.product_family.class: Pim\Bundle\ExcelConnectorBundle\Excel\ProductFamilyExcelBuilder
    pim_excel_connector.excel.object_cache.class:           Pim\Bundle\ExcelConnectorBundle\Excel\ObjectCache

services:
    pim_excel_connector.excel.helper:
        class: %pim_excel_connector.excel.helper.class%

    pim_excel_connector.excel.builder.factory:
        class: %pim_excel_connector.excel.builder.factory.class%
        arguments:
            - '@service_container'

    pim_excel_connector.excel.object_cache:
        class: %pim_excel_connector.excel.object_cache.class%
