default:
    class: Pim\Bundle\InstallerBundle\FixtureLoader\Loader
    order: 100
    multiple: false
    csv:
        reader:            pim_base_connector.reader.file.csv
        reader_options:    {}
        processor_options: {}
    yml:
        reader:            pim_base_connector.reader.file.yaml
        reader_options:    {}
        processor_options: {}
    xlsx:
        reader_options:    {}
        processor_options: {}

xls_init_attribute_groups:
    order: 30
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_init.attribute_group
        processor:      pim_base_connector.processor.attribute_group

xslx_categories:
    order: 30
    multiple: true
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_init.category
        processor:      pim_base_connector.processor.category

xls_init_group_types:
    order: 30
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_init.group_type
        processor:      pim_base_connector.processor.group_type

xls_init_channels:
    order: 30
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_init.channel
        processor:      pim_base_connector.processor.channel

xls_init_association_types:
    order: 40
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_init.association_type
        processor:      pim_base_connector.processor.association_type

xls_init_attributes:
    order: 40
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_init.attribute
        processor:      pim_base_connector.processor.attribute

xls_init_families:
    order: 60
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_init.family
        processor:      pim_base_connector.processor.family
