default:
    class: Pim\Bundle\InstallerBundle\FixtureLoader\Loader
    order: 100
    multiple: false
    csv:
        reader:            pim_base_connector.reader.file.csv
        reader_options:    {}
        processor_options: {}
    yml:
        reader:            pim_base_connector.reader.file.yaml
        reader_options:    {}
        processor_options: {}
    xlsx:
        reader_options:    {}
        processor_options: {}

xlsx_attribute_groups:
    order: 30
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_file.attribute_group
        processor:      pim_base_connector.processor.attribute_group

xslx_categories:
    order: 30
    multiple: true
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_file.category
        processor:      pim_base_connector.processor.category

xlsx_channels:
    order: 30
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_file.channel
        processor:      pim_base_connector.processor.channel

xlsx_attributes:
    order: 40
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_file.attribute
        processor:      pim_base_connector.processor.attribute

xlsx_families:
    order: 60
    file_name: init
    xlsx:
        reader:         pim_excel_connector.reader.xls_file.family
        processor:      pim_base_connector.processor.family
