services:
    pim_transform.transformer.guesser.attribute_option_value:
        class: %pim_transform.transformer.guesser.regexp.class%
        public: false
        arguments:
            - '@pim_excel_connector.transformer.property.conversion_units'
            - %pim_catalog.entity.channel.class%
            - ['/^conversion_units-/']
        tags:
            - { name: pim_transform.transformer.guesser, priority: 40 }
