parameters:
    pim_excel_connector.iterator.file.factory.class:        Pim\Bundle\ExcelConnectorBundle\Iterator\FileIteratorFactory
    pim_excel_connector.iterator.file.xlsx.class:           Pim\Bundle\ExcelConnectorBundle\Iterator\XlsxFileIterator
    pim_excel_connector.iterator.file.xlsx.attribute.class: Pim\Bundle\ExcelConnectorBundle\Iterator\AttributeXlsxFileIterator
    pim_excel_connector.iterator.file.xlsx.family.class:    Pim\Bundle\ExcelConnectorBundle\Iterator\FamilyXlsxFileIterator

services:
    pim_excel_connector.iterator.file.factory:
        class: %pim_excel_connector.iterator.file.factory.class%
