parameters:
    pim_excel_connector.writer.xlsx.class:           Pim\Bundle\ExcelConnectorBundle\Writer\XlsxWriter
    pim_excel_connector.writer.excel_2003_xml.class: Pim\Bundle\ExcelConnectorBundle\Writer\Excel2003XmlWriter

services:
    pim_excel_connector.writer.orm.attribute_group:
        class: %pim_base_connector.writer.orm.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'

    pim_excel_connector.writer.orm.group_type:
        class: %pim_base_connector.writer.orm.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'

    pim_excel_connector.writer.orm.channel:
        class: %pim_base_connector.writer.orm.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'

    pim_excel_connector.writer.orm.family:
        class: %pim_base_connector.writer.orm.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'

    pim_base_connector.writer.xlsx:
        class: %pim_excel_connector.writer.xlsx.class%
        abstract: true
        arguments:
            - '@pim_excel_connector.excel.builder.factory'

    pim_base_connector.writer.xlsx.product:
        parent: pim_base_connector.writer.xlsx
        arguments:
            - '%pim_excel_connector.excel.builder.class%'
            - { worksheet_name: PRODUCTS }

    pim_base_connector.writer.xlsx.product_family:
        parent: pim_base_connector.writer.xlsx
        arguments:
            - '%pim_excel_connector.excel.builder.product_family.class%'

    pim_excel_connector.writer.excel_2003_xml:
        class: %pim_excel_connector.writer.excel_2003_xml.class%
        arguments:
            - @pim_serializer
            - 'excel_2003_xml'
            - %pim_excel_connector.root_dir%/Resources/views/excel_2003_xml_header.txt
            - %pim_excel_connector.root_dir%/Resources/views/excel_2003_xml_footer.txt
