parameters:
    pim_excel_connector.writer.xlsx.class:            Pim\Bundle\ExcelConnectorBundle\Writer\XlsxWriter
    pim_excel_connector.writer.homogeneous_csv.class: Pim\Bundle\ExcelConnectorBundle\Writer\HomogeneousCSVWriter
    pim_excel_connector.writer.excel_2003_xml.class:  Pim\Bundle\ExcelConnectorBundle\Writer\Excel2003XmlWriter

services:
    pim_excel_connector.writer.xlsx:
        class: %pim_excel_connector.writer.xlsx.class%
        abstract: true
        arguments:
            - '@pim_excel_connector.excel.builder.factory'

    pim_excel_connector.writer.homogeneous_csv:
        class: %pim_excel_connector.writer.homogeneous_csv.class%

    pim_excel_connector.writer.xlsx.product:
        parent: pim_excel_connector.writer.xlsx
        arguments:
            - '%pim_excel_connector.excel.builder.class%'
            - { worksheet_name: PRODUCTS }

    pim_excel_connector.writer.xlsx.product_family:
        parent: pim_excel_connector.writer.xlsx
        arguments:
            - '%pim_excel_connector.excel.builder.product_family.class%'

    pim_excel_connector.writer.excel_2003_xml:
        class: %pim_excel_connector.writer.excel_2003_xml.class%
        arguments:
            - @pim_serializer
            - 'excel_2003_xml'
            - %pim_excel_connector.root_dir%/Resources/views/excel_2003_xml_header.txt
            - %pim_excel_connector.root_dir%/Resources/views/excel_2003_xml_footer.txt
